# Cloud Build configuration for Multitool Workflow Web
# Builds and deploys to Google Cloud Run

steps:
  # Build the Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - 'gcr.io/$PROJECT_ID/multitool-workflow-web:$COMMIT_SHA'
      - -t
      - 'gcr.io/$PROJECT_ID/multitool-workflow-web:latest'
      - .

  # Push the Docker image to Container Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/multitool-workflow-web:$COMMIT_SHA'

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/multitool-workflow-web:latest'

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - multitool-workflow-web
      - --image
      - 'gcr.io/$PROJECT_ID/multitool-workflow-web:$COMMIT_SHA'
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      # NOTE: APP_URL must be set to your Cloud Run service URL (e.g., https://multitool-workflow-web-xxxxx-uc.a.run.app)
      # After first deployment, update this value with the actual service URL
      - 'NODE_ENV=production,APP_URL=https://multitool-workflow-web-uc.a.run.app'
      - --set-secrets
      - 'GITHUB_CLIENT_ID=github-client-id:latest,GITHUB_CLIENT_SECRET=github-client-secret:latest,SESSION_SECRET=session-secret:latest'
      - --memory
      - 512Mi
      - --cpu
      - '1'
      - --min-instances
      - '0'
      - --max-instances
      - '10'
      - --timeout
      - 60s
      - --concurrency
      - '80'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/multitool-workflow-web:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/multitool-workflow-web:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

# Timeout for the entire build
timeout: 1200s
