# Cloud Build configuration for Multitool Workflow Web
# Builds and deploys to Google Cloud Run

steps:
  # Build the Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - 'eu-west3-docker.pkg.dev/$PROJECT_ID/multitool-workflow-web/app:$COMMIT_SHA'
      - -t
      - 'eu-west3-docker.pkg.dev/$PROJECT_ID/multitool-workflow-web/app:latest'
      - .

  # Push the Docker image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'eu-west3-docker.pkg.dev/$PROJECT_ID/multitool-workflow-web/app:$COMMIT_SHA'

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'eu-west3-docker.pkg.dev/$PROJECT_ID/multitool-workflow-web/app:latest'

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - multitool-workflow-web
      - --image
      - 'eu-west3-docker.pkg.dev/$PROJECT_ID/multitool-workflow-web/app:$COMMIT_SHA'
      - --region
      - eu-west3
      - --platform
      - managed
      - --allow-unauthenticated
      # VPC connector for reaching VM internal IPs (see docs/VPC-SETUP.md)
      - --vpc-connector
      - projects/multitool-workflow-web/locations/eu-west3/connectors/cloud-run-connector
      - --vpc-egress
      - private-ranges-only
      - --set-env-vars
      # NOTE: APP_URL must be set to your Cloud Run service URL (e.g., https://multitool-workflow-web-xxxxx-uc.a.run.app)
      # After first deployment, update this value with the actual service URL
      # REAPER_AUDIENCE and SCHEDULER_SERVICE_ACCOUNT_EMAIL are required for the reaper endpoint
      - 'NODE_ENV=production,APP_URL=https://multitool-workflow-web-uc.a.run.app,REAPER_AUDIENCE=https://multitool-workflow-web-uc.a.run.app,SCHEDULER_SERVICE_ACCOUNT_EMAIL=scheduler-invoker@multitool-workflow-web.iam.gserviceaccount.com'
      - --set-secrets
      - 'GITHUB_CLIENT_ID=github-client-id:latest,GITHUB_CLIENT_SECRET=github-client-secret:latest,SESSION_SECRET=session-secret:latest'
      - --memory
      - 512Mi
      - --cpu
      - '1'
      - --min-instances
      - '0'
      - --max-instances
      - '10'
      - --timeout
      # 1 hour timeout for long-lived WebSocket connections
      - 3600s
      - --concurrency
      # Lower concurrency to avoid CPU starvation with long-lived WebSocket connections
      - '50'

# Store images in Artifact Registry
images:
  - 'eu-west3-docker.pkg.dev/$PROJECT_ID/multitool-workflow-web/app:$COMMIT_SHA'
  - 'eu-west3-docker.pkg.dev/$PROJECT_ID/multitool-workflow-web/app:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

# Timeout for the entire build
timeout: 1200s
