# Cloud Build configuration for building Agent VM images with Packer
#
# This pipeline:
# 1. Initializes Packer plugins
# 2. Builds the VM image with all dependencies pre-installed
# 3. Cleans up old images (keeps last 5)
#
# Trigger: Pub/Sub (for Cloud Scheduler integration) or manual
# NOT triggered by code changes to avoid unnecessary rebuilds

steps:
  # Step 1: Initialize Packer plugins
  - name: 'hashicorp/packer:1.11'
    entrypoint: packer
    args: [init, packer/agent-vm.pkr.hcl]

  # Step 2: Build the VM image
  - name: 'hashicorp/packer:1.11'
    entrypoint: packer
    args:
      - build
      - -var=project_id=$PROJECT_ID
      - -var=zone=eu-west3-a
      - -var=build_timestamp=$BUILD_ID
      - -var=git_sha=$SHORT_SHA
      - -var=build_id=$BUILD_ID
      - packer/agent-vm.pkr.hcl

  # Step 3: Cleanup old images (keep last 5)
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail

        echo "=== Cleaning up old images ==="

        # List images in family, sorted by creation time (oldest first)
        IMAGES=$(gcloud compute images list \
          --filter="family=multitool-agent AND labels.managed-by=packer" \
          --sort-by="creationTimestamp" \
          --format="value(name)")

        # Count images (handle empty case properly)
        if [ -z "$IMAGES" ]; then
          COUNT=0
        else
          COUNT=$(echo "$IMAGES" | wc -l)
        fi
        KEEP=5

        echo "Found $COUNT images in multitool-agent family"

        if [ "$COUNT" -gt "$KEEP" ]; then
          # Delete oldest images, keeping last N
          DELETE_COUNT=$((COUNT - KEEP))
          echo "Deleting $DELETE_COUNT old images (keeping last $KEEP)"
          echo "$IMAGES" | head -n "$DELETE_COUNT" | while read -r IMAGE; do
            if [ -n "$IMAGE" ]; then
              echo "Deleting image: $IMAGE"
              gcloud compute images delete "$IMAGE" --quiet
            fi
          done
        else
          echo "Only $COUNT images exist, keeping all (threshold: $KEEP)"
        fi

        echo "=== Image cleanup complete ==="

timeout: 3600s # 1 hour timeout for build

options:
  logging: CLOUD_LOGGING_ONLY
