shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@mjackson/headers'
  - semver

overrides:
  chokidar: 4.0.1

onlyBuiltDependencies:
  - '@firebase/util'
  - esbuild
  - protobufjs
  - re2
